server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

logging:
    level:
       com.netflix.eureka: OFF
       netflix:
            discovery: OFF
       org.springframework.web: ERROR
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: /tmp/eureka/eureka.log            