spring:
    h2.console.enabled: true
server:
  port: 10001

logging:
    level:
       org.springframework.web: ERROR
       com.ahorasw.app: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: /tmp/fornecedor/fornecedor-stub.log      