spring:
      datasource:
             url: jdbc:postgresql://localhost:5432/pocdb
             username: pocuser
             password: pocpass
             
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/                                  