/*
 * Java domain class for entity "Usuario" 
 * Created on 2018-09-03 ( Date ISO 2018-09-03 - Time 22:49:30 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.ahorasw.controlevendas.service.dto;

import java.io.Serializable;



/**
 * Domain class for entity "Usuario"
 *
 * @author Telosys Tools Generator
 *
 */
public class UsuarioDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String     idusuario    ;
    private String     responsavel  ;
    private String     perfil       ;
    private String     email        ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UsuarioDTO() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setIdusuario( String idusuario ) {
        this.idusuario = idusuario ;
    }
    public String getIdusuario() {
        return this.idusuario;
    }

    public void setResponsavel( String responsavel ) {
        this.responsavel = responsavel ;
    }
    public String getResponsavel() {
        return this.responsavel;
    }

    public void setPerfil( String perfil ) {
        this.perfil = perfil ;
    }
    public String getPerfil() {
        return this.perfil;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idusuario);
        sb.append("|");
        sb.append(responsavel);
        sb.append("|");
        sb.append(perfil);
        sb.append("|");
        sb.append(email);
        return sb.toString(); 
    } 

}
